title: "Ayan Saha"
email: ayan.saha@rootniklabs.com
description: >- # this means to ignore newlines until "baseurl:"
 Head of R&D at RootNik Labs
baseurl: "/" 
url: "https://rooghz.github.io/" 
twitter_username: evils_paradise
github_username:  rooghz
sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
